server:
    diagnostic_endpoints_enabled: true
    database_file: .config/todolist/database.json
    listen_addr: :8080
    public_url: ""
    auth_enabled: false
    token_auth:
        enabled: false
        client_token: api_password
    base_auth:
        enabled: false
        login: ""
        password: ""
    oidc_auth:
        enabled: false
        client_id: ""
        client_secret: ""
        issuer_url: https://accounts.google.com
        scopes:
            - openid
            - email
            - profile
        cookie_key: kiel4teof4Eoziheigiesh7ooquiepho
        whitelist_emails: []
    telegram:
        enabled: false
        token: ""
        userId: 0
        everyday_agenda:
            enabled: false
            at: 0001-01-01T00:00:00Z
client:
    remote_addr: http://127.0.0.1:8080
    server_token: api_password
